.TH BASENAME 1 "2008-1.01" "pdcore utilities" "User Commands"
.SH NAME
basename \- return non-directory portion of a pathname
.SH SYNOPSIS
.B basename
string [suffix]
.SH DESCRIPTION
Return the filename portion of a path/filename string, optionally stripping
a suffix from the returned filename.
.SH OPTIONS
.TP
None
.SH OPERANDS
.TP
string
Input pathname
.TP
suffix
Suffix to strip from filename after path component removed.
.SH "AUTHORITATIVE DOCUMENTATION"
<http://www.opengroup.org/onlinepubs/9699919799/utilities/basename.html>
.SH VERSION AND COMPLIANCE
Utility version 1.01
.P
Functional compliance with POSIX:2008 (IEEE Std 1003.1-2008;
Shell and Utilities, Base Specifications Issue 7).
.SH UNLICENSE
This is free and unencumbered software released into the public domain,
provided "as is", without warranty of any kind, express or implied. See the
file UNLICENSE and the website <http://unlicense.org> for further details.
