.TH CKSUM 1 "2008-1.01" "pdcore utilities" "User Commands"
.SH NAME
cksum \- report checksum and octet count of file(s)
.SH SYNOPSIS
.B cksum
[file ...]
.SH DESCRIPTION
Display CRC check value and octet count of given file(s).
.SH OPTIONS
.TP
None
.SH OPERANDS
.TP
file
Input file. If none provided, or the filename '-' is passed to cksum,
standard input will be used.
.SH "AUTHORITATIVE DOCUMENTATION"
<http://www.opengroup.org/onlinepubs/9699919799/utilities/cksum.html>
.SH VERSION AND COMPLIANCE
Utility version 1.01
.P
Functional compliance with POSIX:2008 (IEEE Std 1003.1-2008;
Shell and Utilities, Base Specifications Issue 7).
.SH UNLICENSE
This is free and unencumbered software released into the public domain,
provided "as is", without warranty of any kind, express or implied. See the
file UNLICENSE and the website <http://unlicense.org> for further details.
