.TH DIRNAME 1 "2008-1.01" "pdcore utilities" "User Commands"
.SH NAME
dirname \- return the directory portion of a pathname
.SH SYNOPSIS
.B dirname
string
.SH DESCRIPTION
Return the directory portion of a path/filename string.
.SH OPTIONS
.TP
None
.SH OPERANDS
.TP
string
Input pathname
.SH "AUTHORITATIVE DOCUMENTATION"
<http://www.opengroup.org/onlinepubs/9699919799/utilities/dirname.html>
.SH VERSION AND COMPLIANCE
Utility version 1.01
.P
Functional compliance with POSIX:2008 (IEEE Std 1003.1-2008;
Shell and Utilities, Base Specifications Issue 7).
.SH UNLICENSE
This is free and unencumbered software released into the public domain,
provided "as is", without warranty of any kind, express or implied. See the
file UNLICENSE and the website <http://unlicense.org> for further details.
