.TH FALSE 1 "2008-1.01" "pdcore utilities" "User Commands"
.SH NAME
false \- return false value
.SH SYNOPSIS
.B true
.SH DESCRIPTION
Return with a non-zero exit status.
.SH OPTIONS
.TP
None
.SH OPERANDS
.TP
None
.SH "AUTHORITATIVE DOCUMENTATION"
<http://www.opengroup.org/onlinepubs/9699919799/utilities/false.html>
.SH VERSION AND COMPLIANCE
Utility version 1.01
.P
Functional compliance with POSIX:2008 (IEEE Std 1003.1-2008;
Shell and Utilities, Base Specifications Issue 7).
.SH UNLICENSE
This is free and unencumbered software released into the public domain,
provided "as is", without warranty of any kind, express or implied. See the
file UNLICENSE and the website <http://unlicense.org> for further details.
